spring:
  application:
    name: session
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-zone-id: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: ${OPENAI_API_URL:https://api.openai.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,configprops
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jvm.memory.used: true
        process.cpu.usage: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        jvm.memory.used: 0.5,0.95,0.99
        process.cpu.usage: 0.5,0.95,0.99
