spring:
  config:
    import: optional:file:.env[.properties]

  ai:
    vectorstore:
      qdrant:
        host: qdrant
        port: 6333
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://db:5432/database}
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
